@url_dev=http://localhost:3052/v1/api

### Sign Up Shop
POST {{url_dev}}/shop/signup
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe3@example.com",
    "password": "securepassword"
}